import { chromium } from 'playwright'
import assert from 'node:assert/strict'
const browser=await chromium.launch()
try {
  const p=await browser.newPage({viewport:{width:1440,height:1000}}),errores=[]
  p.on('pageerror',e=>errores.push(e.message))
  await p.goto(process.env.URL??'http://127.0.0.1:5173')
  await p.getByRole('button',{name:'Buscar módulo',exact:true}).click()
  await p.locator('#modulo-grafica').click()
  const barra=p.getByRole('navigation',{name:'Menús de la aplicación'})
  for(const nombre of ['Archivo','Edición','Objeto','Herramientas','Escena','Vista','Animación','Módulo','Ventana','Ayuda'])assert.equal(await barra.getByRole('button',{name:nombre,exact:true}).count(),1)
  await barra.getByRole('button',{name:'Herramientas',exact:true}).click()
  await barra.locator('summary').filter({hasText:/^Derivación$/}).click()
  await barra.getByRole('button',{name:'Crear normal…',exact:true}).click()
  await p.getByLabel('Expresión f',{exact:true}).fill('x^2')
  await p.getByLabel('Punto x₀',{exact:true}).fill('0')
  await p.getByRole('button',{name:'Calcular',exact:true}).click()
  await p.getByRole('button',{name:'Añadir resultado como objeto',exact:true}).click()
  const estado=await p.evaluate(()=>JSON.parse(localStorage.getItem('calculadora:estado')))
  assert.equal(estado.estados.grafica.filas.at(-1).src,'x=0')
  await p.evaluate(()=>document.activeElement?.blur())
  await p.keyboard.press('F9')
  assert.equal(await p.getByLabel('Expresión f',{exact:true}).inputValue(),'x^2')
  assert.equal(await p.getByLabel('Punto x₀',{exact:true}).inputValue(),'0')
  await p.getByRole('button',{name:'Cerrar herramienta',exact:true}).click()
  await p.getByRole('button',{name:'Acoplar panel',exact:true}).click()
  await barra.getByRole('button',{name:'Escena',exact:true}).click()
  await barra.locator('summary').filter({hasText:/^Ejes$/}).click()
  assert.equal(await barra.getByRole('button',{name:/Eje Z$/}).isDisabled(),true)
  await p.screenshot({path:'/tmp/calculadora-menu-web.png'})
  await p.keyboard.press('Escape')
  assert.deepEqual(errores,[])
  console.log('Web: barra, normal vertical, inserción, inspector acoplado y disponibilidad contextual correctos')
} finally {await browser.close()}
