import { _electron as electron } from 'playwright'
import assert from 'node:assert/strict'
import { mkdtempSync, readFileSync, readdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
const tmp=mkdtempSync(path.join(tmpdir(),'calc-menus-'))
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;delete env.CALC_URL
const app=await electron.launch({args:['.',`--user-data-dir=${path.join(tmp,'perfil')}`],env})
const errores=[]
try {
  const p=await app.firstWindow()
  p.on('pageerror',e=>errores.push(e.message))
  await p.waitForLoadState('domcontentloaded')
  await p.waitForTimeout(1000)
  await app.evaluate(({BrowserWindow,session},tmp)=>{
    BrowserWindow.getFocusedWindow=()=>BrowserWindow.getAllWindows().at(-1)
    BrowserWindow.prototype.isFocused=function(){return this===BrowserWindow.getFocusedWindow()}
    session.defaultSession.on('will-download',(_e,item)=>item.setSavePath(`${tmp}/${item.getFilename()}`))
  },tmp)
  const menu=async(...ruta)=>{
    await p.evaluate(()=>document.activeElement?.blur?.())
    await app.evaluate(({Menu},ruta)=>{let items=Menu.getApplicationMenu().items,item;for(const nombre of ruta){item=items.find(i=>i.label===nombre);if(!item)throw new Error(`No existe ${nombre}`);if(!item.enabled)throw new Error(`Desactivado ${nombre}`);items=item.submenu?.items??[]}item.click()},ruta)
    await p.waitForTimeout(250)
  }
  const estado=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('calculadora:estado')))
  await p.keyboard.press(process.platform==='darwin'?'Meta+k':'Control+k')
  await p.locator('#modulo-grafica').click()
  await p.waitForTimeout(400)
  await menu('Módulo','Restablecer el módulo')
  await menu('Objeto','Propiedades…')
  await p.locator('.inspector-lista input').first().check()
  await p.getByLabel('Definición',{exact:true}).fill('x^2')
  await p.getByRole('button',{name:'Aplicar definición',exact:true}).click()
  await p.waitForTimeout(500)
  const idOriginal=(await estado()).estados.grafica.filas[0]._id
  assert.ok(idOriginal)
  await menu('Herramientas','Derivación','Crear tangente…')
  await p.getByLabel('Punto x₀',{exact:true}).fill('2')
  await p.getByRole('button',{name:'Calcular',exact:true}).click()
  await p.getByRole('button',{name:'Añadir resultado como objeto',exact:true}).click()
  await p.waitForTimeout(500)
  let s=(await estado()).estados.grafica
  const derivada=s.filas.at(-1)
  assert.ok(derivada.src.includes('4'))
  assert.equal(s._derivados[0].origen,idOriginal)
  await p.getByLabel('Definición',{exact:true}).fill('x^3')
  await p.getByRole('button',{name:'Aplicar definición',exact:true}).click()
  await p.waitForTimeout(600)
  s=(await estado()).estados.grafica
  assert.equal(s.filas[0]._id,idOriginal)
  assert.notEqual(s.filas.at(-1).src,derivada.src)
  await menu('Edición','Deshacer')
  s=(await estado()).estados.grafica
  assert.equal(s.filas[0].src,'x^2')
  assert.equal(s.filas.at(-1).src,derivada.src)
  await p.locator('.inspector-lista input').nth(1).check()
  await menu('Objeto','Organización','Agrupar selección')
  s=(await estado()).estados.grafica
  assert.ok(s._objetos[idOriginal].grupo)
  assert.equal(s._objetos[idOriginal].grupo,s._objetos[s.filas[1]._id].grupo)
  const visibilidad=s.filas.map(f=>f.visible)
  await p.locator('.inspector-lista input').nth(1).uncheck()
  await menu('Objeto','Aislar selección')
  assert.equal((await estado()).estados.grafica.filas.at(-1).visible,false)
  await menu('Objeto','Salir de aislamiento')
  assert.deepEqual((await estado()).estados.grafica.filas.map(f=>f.visible),visibilidad)
  await p.getByRole('button',{name:'Cerrar propiedades'}).click()
  await menu('Escena','Rejilla','Tipo de rejilla','Isométrica')
  assert.equal((await estado()).estados.grafica._escena.sistema,'isometrico')
  await menu('Escena','Ejes','Mostrar ejes')
  assert.equal((await estado()).estados.grafica._escena.vista.ejes,false)
  await menu('Escena','Fondo y guías','Añadir guía…')
  await p.getByLabel('Coordenada',{exact:true}).fill('pi')
  await p.getByRole('dialog').getByRole('button',{name:'Aplicar',exact:true}).click()
  assert.ok(Math.abs((await estado()).estados.grafica._escena.guias[0].valor-Math.PI)<1e-12)
  await menu('Archivo','Importar','Imagen de fondo…')
  const png=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=4;c.height=4;const ctx=c.getContext('2d');ctx.fillStyle='red';ctx.fillRect(0,0,4,4);return c.toDataURL().split(',')[1]})
  await p.getByLabel('Archivo de imagen').setInputFiles({name:'fondo.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')})
  await p.getByRole('button',{name:'Añadir imagen a la escena'}).click()
  await p.waitForTimeout(500)
  assert.equal((await estado()).estados.grafica._escena.imagen.ancho,10)
  await menu('Archivo','Exportar','SVG…')
  await p.waitForTimeout(700)
  const svg=readFileSync(path.join(tmp,readdirSync(tmp).find(f=>f.endsWith('.svg'))),'utf8')
  assert.match(svg,/<svg/);assert.match(svg,/<path/);assert.match(svg,/<image/);assert.ok(!svg.includes('NaN'))
  await menu('Archivo','Importar','Datos CSV en Gráficas…')
  await p.getByLabel('Archivo CSV').setInputFiles({name:'puntos.csv',mimeType:'text/csv',buffer:Buffer.from('x,y\n0,1\n2,3')})
  await p.getByRole('button',{name:'Añadir puntos a Gráficas'}).click()
  await p.waitForTimeout(400)
  assert.equal((await estado()).estados.grafica.filas.at(-1).src,'(2,3)')
  await p.reload();await p.waitForTimeout(600)
  assert.equal((await estado()).estados.grafica.filas[0]._id,idOriginal)
  assert.equal((await estado()).estados.grafica._escena.sistema,'isometrico')
  assert.equal((await estado()).estados.grafica._escena.imagen.ancho,10)
  assert.ok((await estado()).estados.grafica._resultados.length)
  await menu('Archivo','Exportar','Informe de resultados…')
  await p.waitForTimeout(400)
  const informe=readFileSync(path.join(tmp,'resultados-calculadora.html'),'utf8')
  assert.ok(informe.includes((await estado()).estados.grafica._resultados.at(-1).r.metodo))
  await menu('Ventana','Resultados y pasos')
  assert.match(await p.getByRole('region',{name:'Resultados y pasos'}).innerText(),/tangente/)
  await p.getByRole('button',{name:'Cerrar resultados'}).click()
  await menu('Vista','Comparar A y B','Activar')
  await p.getByLabel('Módulo de B').selectOption('grafica')
  await p.getByRole('group',{name:'Qué lado se edita'}).getByRole('button',{name:/^B ·/}).click()
  await menu('Escena','Rejilla','Tipo de rejilla','Polar')
  assert.equal((await estado()).estadosB.grafica._escena.sistema,'polar')
  assert.equal((await estado()).estados.grafica._escena.sistema,'isometrico')
  await p.waitForTimeout(500)
  await menu('Edición','Deshacer')
  assert.equal((await estado()).estadosB.grafica._escena.sistema,'isometrico')
  assert.equal((await estado()).estados.grafica._escena.sistema,'isometrico')
  await menu('Vista','Comparar A y B','Activar')
  await menu('Objeto','Propiedades…')
  await menu('Edición','Seleccionar','Nada')
  await p.locator('.inspector-lista input').first().check()
  await p.getByLabel('Definición',{exact:true}).fill('a*x')
  await p.getByRole('button',{name:'Aplicar definición',exact:true}).click()
  await menu('Animación','Animar parámetro…')
  await p.getByLabel('Duración (segundos)',{exact:true}).fill('1')
  await p.getByRole('dialog').getByRole('button',{name:'Aplicar',exact:true}).click()
  await p.waitForTimeout(150)
  const antes=(await estado()).estados.grafica.params.a.v
  await p.waitForTimeout(250)
  assert.notEqual((await estado()).estados.grafica.params.a.v,antes)
  await menu('Animación','Animar parámetro…')
  await p.getByRole('dialog').press('Escape')
  await p.getByRole('button',{name:'Cerrar propiedades'}).click()
  assert.deepEqual(errores,[])
  console.log('Menús: selección, grupos, aislamiento, dependencias, deshacer A/B, escena, imagen, guías, SVG, CSV, resultados persistentes y animación correctos')
} catch(error) {
  const p = await app.firstWindow(); console.error(await p.locator('.inspector').innerText().catch(()=>'')); console.error(await p.evaluate(()=>JSON.parse(localStorage.getItem('calculadora:estado')).estados.grafica.filas)); await p.screenshot({path:'/tmp/calculadora-menus-fallo.png'}); throw error
} finally {await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{})}
